databases:
  - name: budgettrack
    databaseName: budgettrack
    user: budget

services:
  - type: web
    name: budget
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: budgettrack
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false